import json

with open("lib/l10n/app_ko.arb", "r", encoding="utf-8") as f:
    data = json.load(f)

updates = {
    "dashboardSubtitle": "작은 습관이 모여 완벽을 만들어요. 지치지 않게, 자주, 꾸준하게.",
    "dashboardReadyTitle": "준비 완료",
    "dashboardPrimarySetHint": "{exercise} {count}회, 지금 바로 시작해 볼까요?",
    "activeDaysPill": "{count}일째 운동 중",
    "quickLogHelper": "오늘 하루도 멋지게 숫자를 채워보세요.",
    "decreaseValue": "줄이기",
    "increaseValue": "늘리기",
    "resetLogsTitle": "모든 기록을 지울까요?",
    "resetLogsMessage": "기기에 저장된 모든 운동 기록이 영구적으로 지워져요. 계속할까요?",
    "loadingLogs": "기록을 불러오고 있어요...",
    "recentLogsTitle": "최근 기록",
    "noLogsHint": "오늘 아직 기록이 없어요. 가볍게 한 세트 어떨까요?",
    "noLogsHintHome": "오늘 운동 기록이 없어요. 홈에서 한 세트를 기록해 보세요.",
    "calendarTitle": "나의 리듬",
    "calendarSubtitleHeatmap": "색이 진해질수록 리듬이 탄탄해지고 있어요.",
    "noLogsForDay": "이날은 기록이 없어요. 홈에서 한 세트 기록해 보세요.",
    "settingsThemeSubtitle": "앱 화면 테마를 선택할 수 있어요.",
    "settingsCoachSubtitle": "목표 횟수와 추천 계획을 관리할 수 있어요.",
    "remindersTitle": "알림",
    "remindersSubtitle": "알림 주기와 조용한 시간을 설정할 수 있어요.",
    "allLogsSubtitle": "모든 기록을 날짜와 종목별로 확인해요.",
    "privacyPolicySubtitle": "데이터 처리에 대한 안내를 확인해요.",
    "adPrivacyChoicesSubtitle": "광고 동의 설정을 다시 확인해요.",
    "adPrivacyChoicesUnavailable": "지금은 광고 옵션을 열 수 없어요.",
    "invalidLink": "올바른 링크가 아니에요.",
    "cannotOpenBrowser": "브라우저를 열지 못했어요. 다시 시도해 주세요.",
    "openExternalFailed": "링크를 열지 못했어요.",
    "appUpdateBody": "새로운 버전({version})이 있어요. 최신 기능과 함께 더 나은 앱을 경험해 보세요.",
    "remindersSubheadline": "알림 주기를 설정하면 하루 일과에 맞춰 알림을 보내드려요.",
    "enableRemindersTitle": "알림 켜기",
    "enableRemindersNoSlotsSubtitle": "알림을 보낼 시간이 없어요. 조용한 시간이나 주말 쉬기 설정을 확인해 주세요.",
    "reminderOptimizationTitle": "기록 맞춤 제안",
    "reminderOptimizationEnable": "운동 리듬을 찾을 수 있도록 알림을 켜볼까요?",
    "reminderOptimizationReduceFrequency": "최근 리듬이 여유로워요. {count}분 간격으로 알림을 받아보세요.",
    "reminderOptimizationSkipWeekends": "주말에는 기록이 적네요. 주말 쉬기 옵션을 켜보는 건 어떨까요?",
    "reminderOptimizationPreferredTime": "{time} 즈음에 기록이 많아요. 이 시간에 집중해서 알림을 받아보세요.",
    "weekendsOffSubtitle": "주말에는 알림을 보내지 않아요.",
    "silentNotificationsInfo": "알림은 소리 없이 조용하게 울려요.",
    "permissionDenied": "알림 권한이 필요해요. 기기 설정에서 허용해 주세요.",
    "onboardingSubtitle": "완벽함보다 꾸준함이 중요해요. 1분만 설정하면 바로 시작할 수 있어요.",
    "onboardingQuestion": "어떤 운동을 주로 하시나요?",
    "onboardingHint": "선택한 운동이 홈 화면 가장 앞에 나타나요.",
    "onboardingBaselineTitle": "선택: 최대 횟수 입력",
    "onboardingBaselineSubtitle": "지금 입력하지 않아도 괜찮아요. 코치가 알맞은 횟수를 추천할 때 참고해요.",
    "onboardingBaselineFieldLabel": "한 번에 할 수 있는 최대 횟수",
    "onboardingBaselineFieldHint": "건너뛰어도 나중에 언제든 추가할 수 있어요.",
    "onboardingPushUpSubtitle": "언제 어디서나 간편하게 시작해요.",
    "onboardingPullUpSubtitle": "정확한 자세로 당기는 상체 운동이에요.",
    "onboardingDipsSubtitle": "올바른 각도로 미는 힘을 길러요.",
    "coachFocusTitle": "목표 운동",
    "coachFocusSubtitle": "무리하지 않고 꾸준히 할 수 있게 목표를 맞춰드릴게요.",
    "coachFocusMoveLabel": "주요 운동",
    "coachRecommendedRepsLabel": "추천 횟수",
    "coachRecommendedHint": "최대 횟수의 절반 정도로 설정하면 여유롭게 리듬을 유지할 수 있어요.",
    "coachLastTestedLabel": "마지막 최대 횟수 측정일",
    "coachLastTestedNever": "기록 없음",
    "coachBaselineSubtitle": "현재 최대 횟수와 하루 목표 세트를 설정해 주세요.",
    "coachBaselineLabel": "현재 최대 횟수",
    "coachDailySetGoalLabel": "하루 목표 세트",
    "coachPlanSubtitle": "오늘 기록한 운동을 바탕으로 진행 상황을 보여드릴게요.",
    "coachCompletedSetsLabel": "완료 세트",
    "coachCardReadySubtitle": "오늘의 추천 목표와 진행도를 확인해요.",
    "coachCardSetupSubtitle": "최대 횟수를 입력하면 더 적절한 목표를 추천해 드릴게요.",
    "coachSetBaselineAction": "최대 횟수 입력",
    "coachSetupHint": "최대 횟수를 저장하면 무리하지 않는 선에서 알맞은 세트를 추천해 드릴게요.",
    "coachRetestDueMessage": "2주가 지났어요. 최대 횟수를 다시 측정하면 목표를 새롭게 맞출 수 있어요.",
    "coachQuickLogRecommended": "추천 {count}회",
    "coachRemainingSets": "오늘은 {count}세트 남았어요",
    "gtgInsightsTitle": "나의 기록 분석",
    "gtgInsightsSubtitle": "최근 기록을 분석해서 찾은 나만의 패턴이에요.",
    "gtgInsightBaselineMissing": "최대 횟수를 입력하면 나에게 딱 맞는 가이드를 받아볼 수 있어요.",
    "gtgInsightConsistency": "최근 14일 중 {count}일 동안 운동했어요.",
    "gtgInsightRetestDue": "최대 횟수를 측정한 지 오래됐어요. 새로운 기준을 세워볼까요?",
    "splashTapToSkip": "화면을 눌러 건너뛰기",
    "notifTitle": "운동할 시간",
    "notifBody": "가볍게 한 세트 기록하고 오늘의 리듬을 이어가 보세요.",
    "missionTodayTitle": "오늘의 미션",
    "missionTodaySubtitle": "오늘 다시 운동하게 만드는 작고 꾸준한 계획이에요.",
    "missionRecoverySubtitle": "{count}일 동안 쉬었어요. 가볍게 1세트만 기록하고 리듬을 다시 깨워볼까요?",
    "missionCompleteTitle": "오늘의 미션 완료!",
    "missionCompleteSubtitle": "멋진 리듬이에요. 오늘의 추가 운동은 선택 사항입니다.",
    "missionProgressLabel": "진행 상황",
    "missionRhythmLabel": "주간 리듬",
    "calendarRhythmMessage": "최근 7일 동안 {count7}일 운동했어요. (14일 기준 {count14}일)",
    "calendarRecoveryMessage": "쉬어가는 것도 중요해요. {count}일 쉬었으니 오늘은 가볍게 1세트만 시작해 보세요.",
    "adaptiveCoachTitle": "맞춤 코치",
    "adaptiveCoachSubtitle": "가장 알맞은 운동 계획을 찾아서 추천해 드려요.",
    "adaptiveCoachLocalSource": "기기 설정",
    "adaptiveCoachReasonRetestDue": "최대 횟수 측정 필요",
    "adaptiveCoachReasonRestartAfterGap": "최근 휴식 감지",
    "adaptiveCoachReasonRecoverVolume": "운동량 회복 추천",
    "adaptiveCoachReasonMaintainVolume": "현재 운동량 유지",
    "adaptiveCoachReasonProgressVolume": "안정적인 운동 리듬"
}

for key, val in updates.items():
    if key in data:
        data[key] = val

with open("lib/l10n/app_ko.arb", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

